image: node



stages:
  - build
  - lint
  - deploy

cache:
  paths:
    - node_modules/

#build de l'application
first-job:
 
  stage: build
  script:
    - yarn install --immutable 
  artifacts:
    paths:
    - node_modules



# Lets name our Job eslint, because that's what it's doing.
eslint:
 # tell eslint what stage it is. (This could also be build or test for example)
 stage: lint
 # What scripts do we want to run?
 script:
    # install eslint
    - yarn add eslint
    - cd client
    # Run eslint
    - yarn run eslint src/*.tsx

pages:
  stage: deploy
  script:
  - cd client
  - yarn install
  - yarn run production
  - rm -rf public
  - mv dist/* $CI_PROJECT_DIR/public

  artifacts:
    paths:
    - public



