image: node

before-script:
  - cd client && yarn install

stages:
  - build
  - lint
  - deploy





# Lets name our Job eslint, because that's what it's doing.
eslint:
 # tell eslint what stage it is. (This could also be build or test for example)
 stage: lint
 # What scripts do we want to run?
 script:
    - yarn run lint

pages:
  stage: deploy
  script:
  - yarn run build
  - rm -rf public
  - mv dist/* $CI_PROJECT_DIR/public

  artifacts:
    paths:
    - public



