image: node:latest

stages:
  - build
  - run

# Job's name
first-job:
  # Define stage
  stage: build
  # What to run on the job.
  script:
    - npm install
    - npm install --save-dev ts-loader css-loader html-webpack-plugin mini-css-extract-plugin source-map-loader webpack webpack-cli eslint-webpack-plugin
  artifacts:
    paths:
      - node_modules

second-job:
  stage: run
  script:
    - cd client
    - npm run dev
  artifacts:
    paths:
      - node_modules/
      - client/dist/

second-job-parallel:
  stage: run
  script:
    - echo "I'm running at the same time as second-job!!!"
