image: node

#Ce job doit être exécuté avant les autre car il installe les dépendances
default:
  before_script:
   - cd client && yarn install
  cache:
    paths:
    - client/node_modules


stages:
  - lint
  - deploy

#ce job est pour évaluer le code avec ESlint
eslint:
 stage: lint
 script:
    - yarn run lint

#ce job est pour le déploiement
pages:
  stage: deploy
  script:
    - yarn run build  
  artifacts:
    paths:
    - client/dist

  publish: client/dist



