image: node

cache:
    paths:
    - client/node_modules

#Ce job doit être exécuté en premier pour installer les dépendances
default:
  before_script:
   - cd client && yarn install

stages:
  - lint
  - deploy

#Ce job évalue le code avec ESlint
eslint:
 stage: lint
 script:
    - yarn run lint

#Ce job déploie l'application 
pages:
  stage: deploy
  script:
    - yarn run build  
  artifacts:
    paths:
    - client/dist

  publish: client/dist



