image: node

default:
  before_script:
   - cd client && yarn install

stages:
  #- lint
  - deploy



#eslint:
# stage: lint
# script:
 #   - yarn run lint

pages:
  
  stage: deploy
  variables:
    PUBLIC_URL: https://p2312644.forge.univ-lyon1.fr/tiw8-tp1
  script:
    - yarn run build
  
  artifacts:
    paths:
    - ./dist

  publish: ./dist



